// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkToPSenEOqJndHZWpeZFmjFoMq3ilaxU',
    appId: '1:727349367277:web:289abe7520c7eb9cd257e4',
    messagingSenderId: '727349367277',
    projectId: 'safe-serve-8de99',
    authDomain: 'safe-serve-8de99.firebaseapp.com',
    databaseURL: 'https://safe-serve-8de99-default-rtdb.firebaseio.com',
    storageBucket: 'safe-serve-8de99.firebasestorage.app',
    measurementId: 'G-B2RB0KLNXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiI4gN2cMw549a0JW_FZpqsmhgDG6eJiA',
    appId: '1:727349367277:android:ef08c06fdd0428b8d257e4',
    messagingSenderId: '727349367277',
    projectId: 'safe-serve-8de99',
    databaseURL: 'https://safe-serve-8de99-default-rtdb.firebaseio.com',
    storageBucket: 'safe-serve-8de99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYS0Bwt0XdqOQi03awGWaNv-6X8b9uxP8',
    appId: '1:727349367277:ios:d8e1caae39117e0ad257e4',
    messagingSenderId: '727349367277',
    projectId: 'safe-serve-8de99',
    databaseURL: 'https://safe-serve-8de99-default-rtdb.firebaseio.com',
    storageBucket: 'safe-serve-8de99.firebasestorage.app',
    iosBundleId: 'com.example.safeserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYS0Bwt0XdqOQi03awGWaNv-6X8b9uxP8',
    appId: '1:727349367277:ios:d8e1caae39117e0ad257e4',
    messagingSenderId: '727349367277',
    projectId: 'safe-serve-8de99',
    databaseURL: 'https://safe-serve-8de99-default-rtdb.firebaseio.com',
    storageBucket: 'safe-serve-8de99.firebasestorage.app',
    iosBundleId: 'com.example.safeserve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkToPSenEOqJndHZWpeZFmjFoMq3ilaxU',
    appId: '1:727349367277:web:ad2d74f276239795d257e4',
    messagingSenderId: '727349367277',
    projectId: 'safe-serve-8de99',
    authDomain: 'safe-serve-8de99.firebaseapp.com',
    databaseURL: 'https://safe-serve-8de99-default-rtdb.firebaseio.com',
    storageBucket: 'safe-serve-8de99.firebasestorage.app',
    measurementId: 'G-ZHQ2GWNMMB',
  );
}
