// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';  // ← Generated by `flutterfire configure`

import 'package:safeserve/screens/login_screen/login_screen.dart';
import 'package:safeserve/screens/register_shop/register_shop_form_data.dart';
import 'package:safeserve/screens/register_shop/screen_one/register_shop_screen_one.dart';
import 'package:safeserve/screens/register_shop/screen_two/register_shop_screen_two.dart';
import 'package:safeserve/screens/shop_detail/shop_detail_screen.dart';
import 'package:safeserve/screens/h800_form/h800_form_screen.dart';
import 'package:safeserve/screens/h800_form/h800_form_screen_two.dart';
import 'package:safeserve/screens/h800_form/h800_form_data.dart';
import 'package:safeserve/screens/view_shop_detail/view_shop_detail_screen.dart';
import 'package:safeserve/screens/edit_shop_detail/edit_shop_detail_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // ← This is critical!
  );
  runApp(const SafeServeApp());
}

class SafeServeApp extends StatelessWidget {
  const SafeServeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SafeServe',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(fontFamily: 'Roboto'),
      home: const LoginScreen(),
      routes: {
        '/search': (_) => const PlaceholderPage(title: 'Search'),
        '/menu': (_) => const PlaceholderPage(title: 'Menu'),
        '/add': (_) => const PlaceholderPage(title: 'Add'),
        '/detail': (_) => const PlaceholderPage(title: 'Shop Detail'),
        '/calendar': (_) => const PlaceholderPage(title: 'Calendar'),
        '/dashboard': (_) => const PlaceholderPage(title: 'Dashboard'),
        '/form': (_) => const PlaceholderPage(title: 'Form'),
        '/notifications': (_) => const PlaceholderPage(title: 'Notifications'),
        '/register_shop_screen_one': (ctx) {
          final args = ModalRoute.of(ctx)!.settings.arguments
          as RegisterShopFormData?;
          return RegisterShopScreenOne(
              formData: args ?? RegisterShopFormData());
        },
        '/register_shop_screen_two': (ctx) {
          final args = ModalRoute.of(ctx)!.settings.arguments
          as RegisterShopFormData?;
          return RegisterShopScreenTwo(
              formData: args ?? RegisterShopFormData());
        },
        '/shop_detail': (ctx) {
          final id = ModalRoute.of(ctx)!.settings.arguments as String?;
          return ShopDetailScreen(shopId: id ?? '');
        },
        '/h800_form_screen': (ctx) {
          final args =
          ModalRoute.of(ctx)!.settings.arguments as H800FormData?;
          return H800FormScreen(formData: args ?? H800FormData());
        },
        '/h800_form_screen_two': (ctx) {
          final args =
          ModalRoute.of(ctx)!.settings.arguments as H800FormData?;
          return H800FormScreenTwo(formData: args ?? H800FormData());
        },
        '/view_shop_detail': (_) => const ViewShopDetailScreen(),
        '/edit_shop_detail': (_) => const EditShopDetailScreen(),
      },
    );
  }
}

class PlaceholderPage extends StatelessWidget {
  final String title;
  const PlaceholderPage({super.key, required this.title});

  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: Text(title)),
    body: Center(child: Text(title, style: const TextStyle(fontSize: 20))),
  );
}
