name: safeserve
description: "Safe Serve is a food safety inspections mobile application for Public Health Inspectors (PHIs)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6595
  image_picker: ^1.0.7
<<<<<<< HEAD
  intl: ^0.20.2  # Updated to resolve conflict with table_calendar
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.5.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.1
  geolocator: ^13.0.1
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  flutter_secure_storage: ^9.2.2
  table_calendar: ^3.1.2
=======
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.6.5
  firebase_analytics: ^10.6.1
  geolocator: ^10.1.0
  path_provider: ^2.1.3
  connectivity_plus: ^5.0.2
  flutter_secure_storage: ^9.0.0
  table_calendar: ^3.0.9
  uuid: ^4.0.0
  pin_code_fields: ^8.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
>>>>>>> 151f3e602c2476462654d04fd16c5fc1654e7d0d
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/other/
<<<<<<< HEAD
    - assets/images/shop/
=======
    - assets/images/shop/
    - assets/images/other/profile_placeholder.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
>>>>>>> 151f3e602c2476462654d04fd16c5fc1654e7d0d
