name: safeserve
description: "Safe Serve is a food safety inspections mobile application for Public Health Inspectors (PHIs)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  image_picker: ^1.1.2
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5
  geolocator: ^9.0.2
  path_provider: ^2.1.5
  connectivity_plus: ^4.0.2
  flutter_secure_storage: ^8.1.0
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/other/
    - assets/images/shop/
    - assets/images/other/logo.png