name: safeserve
description: "Safe Serve is a food safety inspections mobile application for Public Health Inspectors (PHIs)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6595
  image_picker: ^1.0.7
  intl: ^0.20.2  # Updated to resolve conflict with table_calendar
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.5.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.1
  geolocator: ^13.0.1
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  flutter_secure_storage: ^9.2.2
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/other/
    - assets/images/shop/